### ISSUE TITLE
在这个train.py下，我没有找到需要链接url，但是源码运行的时候，会报connection  error的错误，并且不能够顺利的运行train.py;还存在的一个问题是您的my_dataloader.py里面的np.load其实是failed  to interpret file as pikle.希望您能解决我的问题

### ISSUE THREAD

**Issue by EillotY** [CommissarMa/MCNN-pytorch#1]

**Comment by CommissarMa** [comment]
connection error是因为你没有启动visdom。你需要先在命令行里运行python -m visdom.server
np.load应该不会有问题吧，只是把密度图加载进来。

**Comment by EillotY** [comment]
感谢回复，之前没用过这个工具visdom ；启动完visdom后，直接运行train.py后，并没有顺利的运行，我再看下你的代码；这是我报的错误：
Traceback (most recent call last):
  File "E:/c3f/MCNN-pytorch-master/train.py", line 41, in <module>
    for i, (img, gt_dmap) in enumerate(dataloader):
  File "C:\Users\Davis_Yuan\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "C:\Users\Davis_Yuan\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 615, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "E:\c3f\MCNN-pytorch-master\my_dataloader.py", line 39, in __getitem__
    gt_dmap = np.load(os.path.join(self.gt_dmap_root, img_name.replace('.jpg', '.npy')))
  File "C:\Users\Davis_Yuan\Anaconda3\lib\site-packages\numpy\lib\npyio.py", line 415, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'data/shanghaitech_part_A/train_data/den\\75.npy'
初次可以看出，问题会出现在my_dataloader里面

**Comment by CommissarMa** [comment]
@EillotY 我知道你的问题了，我在data_preparation里面只是提供了如何生成密度图。除此之外，你需要将ShanghaiTech数据集处理成如下格式：
![image](https://user-images.githubusercontent.com/18243899/58601134-1c30d100-82ba-11e9-9a92-8f360b1da9ef.png)
其中images目录里面放的是.jpg图像，ground_truth目录里面是对应的.npy密度图。
这样就能运行了。

**Comment by chihta-chou** [comment]
你给的链接，train_data/ground_truth里的是 .mat格式的文件非.npy

**Comment by CommissarMa** [comment]
@chihta-chou 你可以使用data_preparation/k_nearest_gaussian_kernal.py来生成.npy格式的ground truth密度图。
